/* Canadian institution directory, institution-level PUBLIC data only (no personal contacts).
   Source: 4orm / KCS Capital Institution Directory v2 (2026-05-24). Applicants only.
   Public fields: tier, province, name, type, approximate assets, HQ city, website. */
window.INSTITUTIONS = [
{"tier": "T1", "prov": "AB", "name": "ATB Financial", "type": "Crown Corp", "assets": "$60.4B (FY24)", "city": "Edmonton", "web": "atb.com"},
{"tier": "T1", "prov": "AB", "name": "Servus Credit Union", "type": "Credit Union", "assets": "$29.4B (2025)", "city": "Edmonton", "web": "servus.ca"},
{"tier": "T1", "prov": "BC", "name": "Beem Credit Union", "type": "Credit Union", "assets": "$14B (2024)", "city": "Kelowna", "web": "beemcreditunion.ca"},
{"tier": "T1", "prov": "BC", "name": "Coast Capital Savings Federal Credit Union", "type": "Credit Union (Federal)", "assets": "$21.9B (2024)", "city": "Surrey", "web": "coastcapitalsavings.com"},
{"tier": "T1", "prov": "BC", "name": "Tru Cooperative Bank (formerly First West CU)", "type": "Credit Union (Federal)", "assets": "$14.3B (2024)", "city": "Langley", "web": "firstwestcu.ca"},
{"tier": "T1", "prov": "BC", "name": "Vancity (Vancouver City Savings CU)", "type": "Credit Union", "assets": "$28.4B (2024)", "city": "Vancouver", "web": "vancity.com"},
{"tier": "T1", "prov": "MB", "name": "Access Credit Union", "type": "Credit Union", "assets": "$13.4B (2024)", "city": "Winkler (RM of Stanley)", "web": "accesscu.ca"},
{"tier": "T1", "prov": "MB", "name": "Assiniboine Credit Union", "type": "Credit Union", "assets": "$9.6B (2025)", "city": "Winnipeg", "web": "acu.ca"},
{"tier": "T1", "prov": "MB", "name": "Steinbach Credit Union", "type": "Credit Union", "assets": "$10.26B (2024)", "city": "Steinbach", "web": "scu.mb.ca"},
{"tier": "T1", "prov": "ON", "name": "Alterna Savings & Credit Union", "type": "Credit Union", "assets": "$13.6B (post-Tandia merger 2026)", "city": "Ottawa", "web": "alterna.ca"},
{"tier": "T1", "prov": "ON", "name": "DUCA Financial Services Credit Union", "type": "Credit Union", "assets": "$7.5B (2024)", "city": "Toronto", "web": "duca.com"},
{"tier": "T1", "prov": "ON", "name": "Equitable Bank (EQB / EQ Bank)", "type": "Schedule I Bank", "assets": "$39.4B (2025)", "city": "Toronto", "web": "equitablebank.ca"},
{"tier": "T1", "prov": "ON", "name": "Libro Credit Union", "type": "Credit Union", "assets": "$8.5B (post-Kawartha merger 2026)", "city": "London", "web": "libro.ca"},
{"tier": "T1", "prov": "ON", "name": "Manulife Bank of Canada", "type": "Schedule I Bank", "assets": "$29B (2025)", "city": "Waterloo", "web": "manulifebank.ca"},
{"tier": "T1", "prov": "ON", "name": "Meridian Credit Union", "type": "Credit Union", "assets": "$26.6B (2024)", "city": "St. Catharines", "web": "meridiancu.ca"},
{"tier": "T1", "prov": "ON", "name": "Tangerine Bank", "type": "Schedule I Bank", "assets": "$51B (2024)", "city": "Toronto", "web": "tangerine.ca"},
{"tier": "T1", "prov": "QC", "name": "Desjardins Group (Mouvement Desjardins)", "type": "Cooperative Financial Group", "assets": "$400B+", "city": "Lévis/Montréal", "web": "desjardins.com"},
{"tier": "T1", "prov": "QC", "name": "Laurentian Bank of Canada", "type": "Schedule I Bank", "assets": "$49.9B (2025)", "city": "Montréal", "web": "laurentianbank.ca"},
{"tier": "T1", "prov": "SK", "name": "Affinity Credit Union", "type": "Credit Union", "assets": "$8.28B (2024)", "city": "Saskatoon", "web": "affinitycu.ca"},
{"tier": "T1", "prov": "SK", "name": "Conexus Credit Union", "type": "Credit Union", "assets": "$16.0B (2026)", "city": "Regina", "web": "conexus.ca"},
{"tier": "T1", "prov": "SK", "name": "Innovation Federal Credit Union", "type": "Credit Union (Federal)", "assets": "$4.24B (2024)", "city": "Swift Current", "web": "innovationcu.ca"},
{"tier": "T2", "prov": "AB", "name": "Bridgewater Bank", "type": "Schedule I Bank", "assets": "$3.3B (2024)", "city": "Calgary", "web": "bridgewaterbank.ca"},
{"tier": "T2", "prov": "AB", "name": "General Bank of Canada", "type": "Schedule I Bank", "assets": "$2B+ (2024)", "city": "Edmonton", "web": "generalbank.ca"},
{"tier": "T2", "prov": "AB", "name": "Peace Hills Trust", "type": "Trust", "assets": "$1B+ AUM", "city": "Edmonton", "web": "peacehills.com"},
{"tier": "T2", "prov": "AB", "name": "Vision Credit Union", "type": "Credit Union", "assets": "$2.5B (2024)", "city": "Camrose", "web": "visioncu.ca"},
{"tier": "T2", "prov": "BC", "name": "Coastal Community Credit Union", "type": "Credit Union", "assets": "$4.3B (post-Integris merger 2026)", "city": "Nanaimo", "web": "cccu.ca"},
{"tier": "T2", "prov": "BC", "name": "Kootenay Savings Credit Union", "type": "Credit Union", "assets": "$1.7B (2024)", "city": "Trail", "web": "kscu.com"},
{"tier": "T2", "prov": "BC", "name": "Peoples Group (Peoples Bank / Peoples Trust)", "type": "Schedule I Bank + Trust", "assets": "multi-$B", "city": "Vancouver", "web": "peoplesgroup.com"},
{"tier": "T2", "prov": "BC", "name": "Salmon Arm Savings & Credit Union (SASCU)", "type": "Credit Union", "assets": "$1.05B (2024)", "city": "Salmon Arm", "web": "sascu.com"},
{"tier": "T2", "prov": "MB", "name": "Cambrian Credit Union", "type": "Credit Union", "assets": "$4.99B (2024)", "city": "Winnipeg", "web": "cambrian.mb.ca"},
{"tier": "T2", "prov": "MB", "name": "Fusion Credit Union", "type": "Credit Union", "assets": "$1.55B (2024)", "city": "Hamiota", "web": "fusioncu.com"},
{"tier": "T2", "prov": "MB", "name": "Stride Credit Union", "type": "Credit Union", "assets": "$1.10B (2024)", "city": "Portage la Prairie", "web": "stridecu.ca"},
{"tier": "T2", "prov": "MB", "name": "Sunrise Credit Union", "type": "Credit Union", "assets": "$1.97B (2024)", "city": "Brandon", "web": "sunrisecu.mb.ca"},
{"tier": "T2", "prov": "NB", "name": "Brunswick Credit Union", "type": "Credit Union", "assets": "$1B (2024)", "city": "Saint John", "web": "brunswickcu.com"},
{"tier": "T2", "prov": "NB", "name": "UNI Coopération financière", "type": "Caisse Populaire (Federal)", "assets": "$5.4B (2023)", "city": "Caraquet", "web": "uni.ca"},
{"tier": "T2", "prov": "NL", "name": "Newfoundland & Labrador Credit Union (NLCU)", "type": "Credit Union", "assets": "$1.5B (2024)", "city": "St. John's", "web": "nlcu.com"},
{"tier": "T2", "prov": "NS", "name": "East Coast Credit Union", "type": "Credit Union", "assets": "$1.55B (2025)", "city": "Dartmouth", "web": "eastcoastcu.ca"},
{"tier": "T2", "prov": "ON", "name": "B2B Bank", "type": "Schedule I Bank", "assets": "", "city": "Toronto", "web": "b2bbank.com"},
{"tier": "T2", "prov": "ON", "name": "Buduchnist Credit Union (BCU Financial)", "type": "Credit Union", "assets": "$1.0B (2024)", "city": "Toronto", "web": "bcufinancial.com"},
{"tier": "T2", "prov": "ON", "name": "CS Alterna Bank", "type": "Schedule I Bank", "assets": "$1.1B (2021)", "city": "Ottawa", "web": "alternabank.ca"},
{"tier": "T2", "prov": "ON", "name": "Caisse populaire Alliance (Caisse Alliance)", "type": "Caisse Populaire", "assets": "$2.6B (2024)", "city": "North Bay", "web": "caissealliance.com"},
{"tier": "T2", "prov": "ON", "name": "Canadian Tire Bank", "type": "Schedule I Bank", "assets": "$7.3B receivables (2024)", "city": "Oakville", "web": "canadiantire.ca"},
{"tier": "T2", "prov": "ON", "name": "Community Trust Company", "type": "Trust", "assets": "$1.2B+ (2025)", "city": "Mississauga", "web": "communitytrust.ca"},
{"tier": "T2", "prov": "ON", "name": "Fairstone Bank of Canada", "type": "Schedule I Bank", "assets": "$5B+ group", "city": "Toronto", "web": "fairstone.ca"},
{"tier": "T2", "prov": "ON", "name": "FirstOntario Credit Union", "type": "Credit Union", "assets": "$6.6B (2024)", "city": "Stoney Creek", "web": "firstontario.com"},
{"tier": "T2", "prov": "ON", "name": "Haventree Bank", "type": "Schedule I Bank", "assets": "$3.9B (2025)", "city": "Toronto", "web": "haventreebank.com"},
{"tier": "T2", "prov": "ON", "name": "HomeEquity Bank", "type": "Schedule I Bank", "assets": "$6B+ portfolio", "city": "Toronto", "web": "homeequitybank.ca"},
{"tier": "T2", "prov": "ON", "name": "Kindred Credit Union", "type": "Credit Union", "assets": "$2.3B (2024)", "city": "Kitchener", "web": "kindredcu.com"},
{"tier": "T2", "prov": "ON", "name": "MCAN Mortgage Corporation (MCAN Financial)", "type": "Loan Company (Federal)", "assets": "$5.3B (2024)", "city": "Toronto", "web": "mcanfinancial.com"},
{"tier": "T2", "prov": "ON", "name": "Mainstreet Credit Union", "type": "Credit Union", "assets": "$1.1B (2024)", "city": "Chatham", "web": "mainstreetcu.ca"},
{"tier": "T2", "prov": "ON", "name": "Northern Credit Union", "type": "Credit Union", "assets": "$2.5B (2025)", "city": "Sault Ste. Marie", "web": "northerncu.com"},
{"tier": "T2", "prov": "ON", "name": "RFA Bank of Canada", "type": "Schedule I Bank", "assets": "$2B+ (2024)", "city": "Toronto", "web": "rfa.ca"},
{"tier": "T2", "prov": "ON", "name": "Ukrainian Credit Union", "type": "Credit Union", "assets": "$1.3B (2024)", "city": "Toronto", "web": "ukrainiancu.com"},
{"tier": "T2", "prov": "ON", "name": "VersaBank", "type": "Schedule I Bank", "assets": "$5.8B (2025)", "city": "London", "web": "versabank.com"},
{"tier": "T2", "prov": "ON", "name": "Windsor Family Credit Union (WFCU)", "type": "Credit Union", "assets": "$5.2B (2024)", "city": "Windsor", "web": "mywfcu.ca"},
{"tier": "T2", "prov": "ON", "name": "Your Neighbourhood Credit Union (YNCU)", "type": "Credit Union", "assets": "$3.9B (post-Comtech Fire merger 2025)", "city": "Kitchener", "web": "yncu.com"},
{"tier": "T2", "prov": "PE", "name": "Provincial Credit Union", "type": "Credit Union", "assets": "$1B (2021)", "city": "Charlottetown", "web": "provincialcu.com"},
{"tier": "T2", "prov": "SK", "name": "First Nations Bank of Canada", "type": "Schedule I Bank", "assets": "$1.48B (2025)", "city": "Saskatoon", "web": "fnbc.ca"},
{"tier": "T2", "prov": "SK", "name": "Prosperity Credit Union", "type": "Credit Union", "assets": "$2.1B (2025)", "city": "Rosetown", "web": "prosperitycu.ca"},
{"tier": "T3", "prov": "AB", "name": "1st Choice Savings & Credit Union", "type": "Credit Union", "assets": "$831M (2024)", "city": "Lethbridge", "web": "1stchoicesavings.ca"},
{"tier": "T3", "prov": "AB", "name": "Bow Valley Credit Union", "type": "Credit Union", "assets": "$606M (2024)", "city": "Cochrane", "web": "bowvalleycu.com"},
{"tier": "T3", "prov": "AB", "name": "Calgary Police Credit Union", "type": "Credit Union", "assets": "", "city": "Calgary", "web": "calgarypolicecu.com"},
{"tier": "T3", "prov": "AB", "name": "Christian Credit Union", "type": "Credit Union", "assets": "$269M (2024)", "city": "Edmonton", "web": "christiancu.ca"},
{"tier": "T3", "prov": "AB", "name": "Digital Commerce Bank (DCBank)", "type": "Schedule I Bank", "assets": "$96M (2024)", "city": "Calgary", "web": "dcbank.ca"},
{"tier": "T3", "prov": "AB", "name": "Khalsa Credit Union (Alberta)", "type": "Credit Union", "assets": "", "city": "Calgary", "web": "kcufinancial.com"},
{"tier": "T3", "prov": "AB", "name": "Lakeland Credit Union", "type": "Credit Union", "assets": "$715M (2024)", "city": "Bonnyville", "web": "lakelandcreditunion.com"},
{"tier": "T3", "prov": "AB", "name": "Rocky Credit Union", "type": "Credit Union", "assets": "$474M (2024)", "city": "Rocky Mountain House", "web": "rockycreditunion.com"},
{"tier": "T3", "prov": "AB", "name": "TransCanada Credit Union", "type": "Credit Union", "assets": "", "city": "Calgary", "web": ""},
{"tier": "T3", "prov": "AB", "name": "Vermilion Credit Union", "type": "Credit Union", "assets": "$273M (2024)", "city": "Vermilion", "web": "vermilioncreditunion.com"},
{"tier": "T3", "prov": "BC", "name": "Bulkley Valley Credit Union", "type": "Credit Union", "assets": "$598M (2024)", "city": "Smithers", "web": "bvcu.com"},
{"tier": "T3", "prov": "BC", "name": "Cascadia Credit Union", "type": "Credit Union", "assets": "$876M (2025 est)", "city": "Summerland", "web": "cascadiacu.com"},
{"tier": "T3", "prov": "BC", "name": "Community Savings Credit Union", "type": "Credit Union", "assets": "$922M (2024)", "city": "Surrey", "web": "comsavings.com"},
{"tier": "T3", "prov": "BC", "name": "Creston & District Credit Union", "type": "Credit Union", "assets": "$300M (est)", "city": "Creston", "web": "cdcu.com"},
{"tier": "T3", "prov": "BC", "name": "Greater Vancouver Community Credit Union (GVC)", "type": "Credit Union", "assets": "$218M (2024)", "city": "Burnaby", "web": "gvccu.com"},
{"tier": "T3", "prov": "BC", "name": "Khalsa Credit Union", "type": "Credit Union", "assets": "$821M (2024)", "city": "Surrey", "web": "khalsacreditunion.ca"},
{"tier": "T3", "prov": "BC", "name": "Ladysmith & District Credit Union", "type": "Credit Union", "assets": "$317M (2024)", "city": "Ladysmith", "web": "ldcu.ca"},
{"tier": "T3", "prov": "BC", "name": "Lake View Credit Union", "type": "Credit Union", "assets": "$375M (2024)", "city": "Dawson Creek", "web": "lakeviewcreditunion.com"},
{"tier": "T3", "prov": "BC", "name": "Nelson & District Credit Union", "type": "Credit Union", "assets": "$317M (2024)", "city": "Nelson", "web": "nelsoncu.com"},
{"tier": "T3", "prov": "BC", "name": "Northern Savings Credit Union", "type": "Credit Union", "assets": "$797M (2024)", "city": "Prince Rupert", "web": "northsave.com"},
{"tier": "T3", "prov": "BC", "name": "Sharons Credit Union", "type": "Credit Union", "assets": "$565M (2024)", "city": "Coquitlam", "web": "sharons.ca"},
{"tier": "T3", "prov": "BC", "name": "StellerVista Credit Union", "type": "Credit Union", "assets": "$731M (2024)", "city": "Cranbrook", "web": "stellervista.com"},
{"tier": "T3", "prov": "BC", "name": "Vancouver Firefighters' Credit Union", "type": "Credit Union", "assets": "", "city": "Vancouver", "web": "vanfirecu.com"},
{"tier": "T3", "prov": "BC", "name": "VantageOne Credit Union", "type": "Credit Union", "assets": "$484M (2024)", "city": "Vernon", "web": "vantageone.net"},
{"tier": "T3", "prov": "BC", "name": "Williams Lake & District Credit Union", "type": "Credit Union", "assets": "$414M (2024)", "city": "Williams Lake", "web": "wldcu.com"},
{"tier": "T3", "prov": "MB", "name": "Belgian-Alliance Credit Union", "type": "Credit Union", "assets": "$239M (2024)", "city": "Winnipeg", "web": "belgianalliancecu.mb.ca"},
{"tier": "T3", "prov": "MB", "name": "Compass Credit Union", "type": "Credit Union", "assets": "$233M (2024)", "city": "Brandon", "web": "compasscu.ca"},
{"tier": "T3", "prov": "MB", "name": "Flin Flon Credit Union", "type": "Credit Union", "assets": "", "city": "Flin Flon", "web": "flinfloncu.com"},
{"tier": "T3", "prov": "MB", "name": "Me-Dian Credit Union", "type": "Credit Union", "assets": "$134M (2024)", "city": "Winnipeg", "web": "mediancu.mb.ca"},
{"tier": "T3", "prov": "MB", "name": "Niverville Credit Union", "type": "Credit Union", "assets": "$537M (2024)", "city": "Niverville", "web": "nivervillecu.mb.ca"},
{"tier": "T3", "prov": "MB", "name": "Rosenort Credit Union", "type": "Credit Union", "assets": "$765M (2024)", "city": "Rosenort", "web": "rcu.ca"},
{"tier": "T3", "prov": "MB", "name": "Swan Valley Credit Union", "type": "Credit Union", "assets": "$368M (2024)", "city": "Swan River", "web": "svcu.mb.ca"},
{"tier": "T3", "prov": "MB", "name": "Winnipeg Police Credit Union", "type": "Credit Union", "assets": "$216M (2024)", "city": "Winnipeg", "web": "wpcu.ca"},
{"tier": "T3", "prov": "NB", "name": "Beaubear Credit Union", "type": "Credit Union", "assets": "", "city": "Miramichi", "web": "beaubear.ca"},
{"tier": "T3", "prov": "NB", "name": "Blackville Credit Union", "type": "Credit Union", "assets": "", "city": "Blackville", "web": "blackvillecu.ca"},
{"tier": "T3", "prov": "NB", "name": "NBTA Credit Union", "type": "Credit Union", "assets": "", "city": "Fredericton", "web": "nbtacu.nb.ca"},
{"tier": "T3", "prov": "NB", "name": "OMISTA Credit Union", "type": "Credit Union", "assets": "", "city": "Moncton", "web": "omista.com"},
{"tier": "T3", "prov": "NB", "name": "The Credit Union (Dalhousie)", "type": "Credit Union", "assets": "", "city": "Dalhousie", "web": "thecreditu.ca"},
{"tier": "T3", "prov": "NL", "name": "Atlantic Edge Credit Union", "type": "Credit Union", "assets": "$500M (est)", "city": "Marystown", "web": "atlanticedgecu.ca"},
{"tier": "T3", "prov": "NL", "name": "Community Credit Union (NL)", "type": "Credit Union", "assets": "", "city": "Bay Roberts", "web": "ccunl.ca"},
{"tier": "T3", "prov": "NL", "name": "Public Service Credit Union (NL)", "type": "Credit Union", "assets": "$43M", "city": "St. John's", "web": "pscu.ca"},
{"tier": "T3", "prov": "NL", "name": "Venture Credit Union", "type": "Credit Union", "assets": "$34M", "city": "Gander", "web": "venturecu.ca"},
{"tier": "T3", "prov": "NS", "name": "Acadian Credit Union (Caisse populaire acadienne)", "type": "Caisse Populaire", "assets": "", "city": "Chéticamp", "web": "acadiancreditu.ca"},
{"tier": "T3", "prov": "NS", "name": "Bay St. Lawrence Credit Union", "type": "Credit Union", "assets": "", "city": "St. Margaret's Village", "web": ""},
{"tier": "T3", "prov": "NS", "name": "Caisse populaire de Clare", "type": "Caisse Populaire", "assets": "", "city": "Church Point", "web": "caissepopclare.com"},
{"tier": "T3", "prov": "NS", "name": "Cape Breton Credit Union", "type": "Credit Union", "assets": "", "city": "Sydney", "web": "sccu.ca"},
{"tier": "T3", "prov": "NS", "name": "Coastal Financial Credit Union", "type": "Credit Union", "assets": "", "city": "Yarmouth", "web": "coastalfinancial.ca"},
{"tier": "T3", "prov": "NS", "name": "Credit Union Atlantic (CUA)", "type": "Credit Union", "assets": "$735M", "city": "Halifax", "web": "cua.com"},
{"tier": "T3", "prov": "NS", "name": "Dominion Credit Union", "type": "Credit Union", "assets": "", "city": "Dominion", "web": "dominioncreditunion.ca"},
{"tier": "T3", "prov": "NS", "name": "Glace Bay Central Credit Union", "type": "Credit Union", "assets": "$200M (est)", "city": "Glace Bay", "web": "glacebaycentralcreditunion.com"},
{"tier": "T3", "prov": "NS", "name": "League Savings & Mortgage Company", "type": "Loan Company (Federal)", "assets": "", "city": "Halifax", "web": "lsm.ca"},
{"tier": "T3", "prov": "NS", "name": "Mosaik Credit Union", "type": "Credit Union", "assets": "", "city": "Truro", "web": "communitycreditunion.ns.ca"},
{"tier": "T3", "prov": "NS", "name": "New Waterford Credit Union", "type": "Credit Union", "assets": "", "city": "New Waterford", "web": "newwaterfordcreditunion.com"},
{"tier": "T3", "prov": "NS", "name": "Princess Credit Union", "type": "Credit Union", "assets": "", "city": "Sydney Mines", "web": "princesscreditunion.ca"},
{"tier": "T3", "prov": "NS", "name": "Public Service Commission Employees' CU", "type": "Credit Union", "assets": "", "city": "Halifax", "web": ""},
{"tier": "T3", "prov": "NS", "name": "St. Joseph's Credit Union", "type": "Credit Union", "assets": "", "city": "Petit-de-Grat", "web": "stjosephscreditu.ca"},
{"tier": "T3", "prov": "NS", "name": "Sydney Credit Union", "type": "Credit Union", "assets": "", "city": "Sydney", "web": "sydneycreditunion.com"},
{"tier": "T3", "prov": "NS", "name": "Teachers Plus Credit Union", "type": "Credit Union", "assets": "", "city": "Bedford", "web": "teachersplus.ca"},
{"tier": "T3", "prov": "NS", "name": "Valley Credit Union", "type": "Credit Union", "assets": "", "city": "Waterville", "web": "valleycreditunion.com"},
{"tier": "T3", "prov": "NS", "name": "iNova Credit Union", "type": "Credit Union", "assets": "", "city": "Halifax", "web": "inovacreditunion.coop"},
{"tier": "T3", "prov": "ON", "name": "Adjala Credit Union (Adjala Savings)", "type": "Credit Union", "assets": "", "city": "Colgan", "web": "adjala.ca"},
{"tier": "T3", "prov": "ON", "name": "Bay Credit Union", "type": "Credit Union", "assets": "$89M (2024)", "city": "Thunder Bay", "web": "baycreditunion.com"},
{"tier": "T3", "prov": "ON", "name": "Dundalk District Credit Union", "type": "Credit Union", "assets": "$71M (2024)", "city": "Dundalk", "web": "dundalkcu.ca"},
{"tier": "T3", "prov": "ON", "name": "Effort Trust Company", "type": "Trust", "assets": "", "city": "Hamilton", "web": "efforttrust.com"},
{"tier": "T3", "prov": "ON", "name": "Equity Credit Union", "type": "Credit Union", "assets": "$370M (2024)", "city": "Ajax", "web": "equitycu.com"},
{"tier": "T3", "prov": "ON", "name": "Fort York Community Credit Union", "type": "Credit Union", "assets": "", "city": "Toronto", "web": "fortyork.com"},
{"tier": "T3", "prov": "ON", "name": "Frontline Financial Credit Union", "type": "Credit Union", "assets": "", "city": "Ottawa", "web": "frontlinecu.com"},
{"tier": "T3", "prov": "ON", "name": "Ganaraska Credit Union", "type": "Credit Union", "assets": "$202M (2024)", "city": "Port Hope", "web": "ganaraskacu.com"},
{"tier": "T3", "prov": "ON", "name": "Golden Horseshoe Credit Union", "type": "Credit Union", "assets": "", "city": "Hamilton", "web": "ghcu.ca"},
{"tier": "T3", "prov": "ON", "name": "Healthcare & Municipal Employees' CU (HMECU)", "type": "Credit Union", "assets": "$329M (2024)", "city": "Hamilton", "web": "hmecu.com"},
{"tier": "T3", "prov": "ON", "name": "IC Savings (Italian Canadian Savings CU)", "type": "Credit Union", "assets": "$939M (2024)", "city": "Toronto", "web": "icsavings.ca"},
{"tier": "T3", "prov": "ON", "name": "Kingston Community Credit Union (KCCU)", "type": "Credit Union", "assets": "$225M (2024)", "city": "Kingston", "web": "kccu.ca"},
{"tier": "T3", "prov": "ON", "name": "Korean (Toronto) Credit Union", "type": "Credit Union", "assets": "$27M (2024)", "city": "Thornhill", "web": "koreancu.com"},
{"tier": "T3", "prov": "ON", "name": "Korean Catholic Church Credit Union", "type": "Credit Union", "assets": "", "city": "North York", "web": "kcccu.ca"},
{"tier": "T3", "prov": "ON", "name": "L.I.U.N.A. Local 183 Credit Union", "type": "Credit Union", "assets": "", "city": "Vaughan", "web": "local183cu.ca"},
{"tier": "T3", "prov": "ON", "name": "Lighthouse Credit Union", "type": "Credit Union", "assets": "$248M (2024)", "city": "Toronto", "web": "lighthousecu.ca"},
{"tier": "T3", "prov": "ON", "name": "Luminus Financial (CU)", "type": "Credit Union", "assets": "$200M+ (2024)", "city": "Toronto", "web": "luminusfinancial.com"},
{"tier": "T3", "prov": "ON", "name": "Motor City Community Credit Union", "type": "Credit Union", "assets": "$577M (2024)", "city": "Windsor", "web": "mcccu.com"},
{"tier": "T3", "prov": "ON", "name": "Moya Financial Credit Union", "type": "Credit Union", "assets": "$405M (2024)", "city": "Toronto (Etobicoke)", "web": "moyafinancial.ca"},
{"tier": "T3", "prov": "ON", "name": "Northern Birch Credit Union", "type": "Credit Union", "assets": "$201M (2024)", "city": "Toronto", "web": "northernbirchcu.com"},
{"tier": "T3", "prov": "ON", "name": "OP Credit Union (Finnish)", "type": "Credit Union", "assets": "", "city": "Toronto", "web": "finnishcu.com"},
{"tier": "T3", "prov": "ON", "name": "OPP Association Credit Union (OPPACU)", "type": "Credit Union", "assets": "$264M (2024)", "city": "Barrie", "web": "oppacu.com"},
{"tier": "T3", "prov": "ON", "name": "Ontario Educational Credit Union (OECU)", "type": "Credit Union", "assets": "", "city": "Mississauga", "web": "oecu.on.ca"},
{"tier": "T3", "prov": "ON", "name": "Oshawa Community Credit Union", "type": "Credit Union", "assets": "$145M (2024)", "city": "Oshawa", "web": "oshawacu.com"},
{"tier": "T3", "prov": "ON", "name": "Parama Credit Union", "type": "Credit Union", "assets": "$592M (2024)", "city": "Toronto", "web": "parama.ca"},
{"tier": "T3", "prov": "ON", "name": "Pathwise Credit Union (formerly AWCCU)", "type": "Credit Union", "assets": "$424M (2024)", "city": "Oshawa", "web": "pathwise.ca"},
{"tier": "T3", "prov": "ON", "name": "PenFinancial Credit Union", "type": "Credit Union", "assets": "$797M (2024)", "city": "Welland", "web": "penfinancial.com"},
{"tier": "T3", "prov": "ON", "name": "Resurrection Credit Union", "type": "Credit Union", "assets": "", "city": "Toronto", "web": "rpcul.com"},
{"tier": "T3", "prov": "ON", "name": "Rogers Bank", "type": "Schedule I Bank", "assets": "$791M (2024)", "city": "Toronto", "web": "rogersbank.com"},
{"tier": "T3", "prov": "ON", "name": "Southwest Regional Credit Union", "type": "Credit Union", "assets": "$231M (2024)", "city": "Sarnia", "web": "southwestcu.com"},
{"tier": "T3", "prov": "ON", "name": "St. Stanislaus-St. Casimir's Polish Parishes CU", "type": "Credit Union", "assets": "$538M (2024)", "city": "Toronto", "web": "polcu.com"},
{"tier": "T3", "prov": "ON", "name": "Sudbury Credit Union", "type": "Credit Union", "assets": "$608M (2024)", "city": "Sudbury", "web": "sudburycu.com"},
{"tier": "T3", "prov": "ON", "name": "Taiwanese-Canadian Toronto Credit Union", "type": "Credit Union", "assets": "", "city": "Markham", "web": "tctcu.com"},
{"tier": "T3", "prov": "ON", "name": "Talka Credit Union (Lithuanian)", "type": "Credit Union", "assets": "", "city": "Hamilton", "web": "talka.ca"},
{"tier": "T3", "prov": "ON", "name": "The Energy Credit Union", "type": "Credit Union", "assets": "$92M (2024)", "city": "Toronto", "web": "theenergycu.com"},
{"tier": "T3", "prov": "ON", "name": "The Police Credit Union (TPCU)", "type": "Credit Union", "assets": "", "city": "Toronto", "web": "tpcu.on.ca"},
{"tier": "T3", "prov": "ON", "name": "Thorold Community Credit Union", "type": "Credit Union", "assets": "", "city": "Thorold", "web": "thoroldcu.com"},
{"tier": "T3", "prov": "ON", "name": "Vancity Community Investment Bank (VCIB)", "type": "Schedule I Bank", "assets": "small", "city": "Toronto", "web": "vancitycommunityinvestmentbank.ca"},
{"tier": "T3", "prov": "ON", "name": "Wealth One Bank of Canada", "type": "Schedule I Bank", "assets": "$516M (2025)", "city": "Toronto", "web": "wealthonebankofcanada.com"},
{"tier": "T3", "prov": "ON", "name": "Your Credit Union", "type": "Credit Union", "assets": "$393M (2024)", "city": "Ottawa", "web": "yourcu.com"},
{"tier": "T3", "prov": "PE", "name": "Consolidated Credit Union", "type": "Credit Union", "assets": "", "city": "Summerside", "web": "consolidatedcreditu.com"},
{"tier": "T3", "prov": "PE", "name": "Morell Credit Union", "type": "Credit Union", "assets": "", "city": "Morell", "web": "morellcreditu.com"},
{"tier": "T3", "prov": "PE", "name": "Souris Credit Union", "type": "Credit Union", "assets": "", "city": "Souris", "web": "souriscreditu.com"},
{"tier": "T3", "prov": "SK", "name": "Accent Credit Union", "type": "Credit Union", "assets": "$339M (2024)", "city": "Quill Lake", "web": "accentcu.ca"},
{"tier": "T3", "prov": "SK", "name": "Bengough Credit Union", "type": "Credit Union", "assets": "", "city": "Bengough", "web": "bengoughcu.ca"},
{"tier": "T3", "prov": "SK", "name": "Biggar & District Credit Union", "type": "Credit Union", "assets": "$317M (2024)", "city": "Biggar", "web": "biggarcu.com"},
{"tier": "T3", "prov": "SK", "name": "Bruno Savings & Credit Union", "type": "Credit Union", "assets": "", "city": "Bruno", "web": "brunocu.ca"},
{"tier": "T3", "prov": "SK", "name": "Churchbridge Credit Union", "type": "Credit Union", "assets": "", "city": "Churchbridge", "web": "churchbridgecu.com"},
{"tier": "T3", "prov": "SK", "name": "Crossroads Credit Union", "type": "Credit Union", "assets": "$373M (2024)", "city": "Canora", "web": "crossroadscu.ca"},
{"tier": "T3", "prov": "SK", "name": "Dodsland & District Credit Union", "type": "Credit Union", "assets": "", "city": "Dodsland", "web": "dodslandcu.com"},
{"tier": "T3", "prov": "SK", "name": "Edam Credit Union", "type": "Credit Union", "assets": "", "city": "Edam", "web": "edamcu.ca"},
{"tier": "T3", "prov": "SK", "name": "Kerrobert Credit Union", "type": "Credit Union", "assets": "", "city": "Kerrobert", "web": "kerrobertcu.com"},
{"tier": "T3", "prov": "SK", "name": "Lafleche Credit Union", "type": "Credit Union", "assets": "", "city": "Lafleche", "web": "laflechecu.ca"},
{"tier": "T3", "prov": "SK", "name": "Luseland Credit Union", "type": "Credit Union", "assets": "", "city": "Luseland", "web": "luselandcu.ca"},
{"tier": "T3", "prov": "SK", "name": "North Valley Credit Union", "type": "Credit Union", "assets": "", "city": "Esterhazy", "web": "northvalleycu.com"},
{"tier": "T3", "prov": "SK", "name": "Prairie Pride Credit Union", "type": "Credit Union", "assets": "", "city": "Alameda", "web": "prairepridecu.com"},
{"tier": "T3", "prov": "SK", "name": "Radius Credit Union", "type": "Credit Union", "assets": "$607M (2024)", "city": "Ogema", "web": "radiuscu.com"},
{"tier": "T3", "prov": "SK", "name": "Raymore Credit Union", "type": "Credit Union", "assets": "$240M (2024)", "city": "Raymore", "web": "raymorecu.com"},
{"tier": "T3", "prov": "SK", "name": "Rockglen-Killdeer Credit Union", "type": "Credit Union", "assets": "", "city": "Rockglen", "web": "rkcu.ca"},
{"tier": "T3", "prov": "SK", "name": "Sandhills Credit Union", "type": "Credit Union", "assets": "$109M (2024)", "city": "Leader", "web": "sandhillscu.com"},
{"tier": "T3", "prov": "SK", "name": "Saskatoon City Employees Credit Union", "type": "Credit Union", "assets": "", "city": "Saskatoon", "web": "scecu.com"},
{"tier": "T3", "prov": "SK", "name": "St. Gregor Credit Union", "type": "Credit Union", "assets": "", "city": "St. Gregor", "web": ""},
{"tier": "T3", "prov": "SK", "name": "Stoughton Credit Union", "type": "Credit Union", "assets": "", "city": "Stoughton", "web": "stoughtoncu.com"},
{"tier": "T3", "prov": "SK", "name": "TCU Financial Group Credit Union", "type": "Credit Union", "assets": "$722M (2024)", "city": "Saskatoon", "web": "tcufinancialgroup.com"},
{"tier": "T3", "prov": "SK", "name": "Turtleford Credit Union", "type": "Credit Union", "assets": "$117M (2024)", "city": "Turtleford", "web": "turtlefordcu.ca"},
{"tier": "T3", "prov": "SK", "name": "Unity Credit Union", "type": "Credit Union", "assets": "$374M (2024)", "city": "Unity", "web": "unitycu.ca"},
{"tier": "T3", "prov": "SK", "name": "Weyburn Credit Union", "type": "Credit Union", "assets": "$734M (2024)", "city": "Weyburn", "web": "weyburncu.ca"}
];
